## Process dict items

Let us understand how we can process the items in dicts.
* We have a function called as `items` which return all the items in the dict as a list like object.
* Each element in the list like object that is generated because of `items` will be of type tuple.

In [1]:
order_item_subtotals = {
    1: 299.98,
    2: 199.99,
    3: 250.0,
    4: 129.99
}

In [2]:
order_item_subtotals

{1: 299.98, 2: 199.99, 3: 250.0, 4: 129.99}

In [3]:
type(order_item_subtotals)

dict

In [4]:
order_item_subtotals.items()

dict_items([(1, 299.98), (2, 199.99), (3, 250.0), (4, 129.99)])

In [5]:
for ois in order_item_subtotals.items():
    print(f'The type of {ois} is {type(ois)}')

The type of (1, 299.98) is <class 'tuple'>
The type of (2, 199.99) is <class 'tuple'>
The type of (3, 250.0) is <class 'tuple'>
The type of (4, 129.99) is <class 'tuple'>

* Each value in the dict can be of basic type like above or it can be of complex type.
* In the below example each value in the dict is of type list.

In [6]:
order_item_subtotals = {
    1: [299.98],
    2: [199.99, 250.0, 129.99],
    4: [49.98, 150.0, 199.92],
    5: [299.98, 299.95, 99.96, 299.98, 129.99],
    7: [199.99, 299.98, 79.95],
    8: [179.97, 299.95, 199.92, 50.0]
}

* Following are some of the real examples on top of `dict` objects like above. The keys in the dicts are nothing but order ids.
  * Get the number of items for each order id.
  * Get the revenue for each order id.

In [7]:
order_item_subtotals.items()

dict_items([(1, [299.98]), (2, [199.99, 250.0, 129.99]), (4, [49.98, 150.0, 199.92]), (5, [299.98, 299.95, 99.96, 299.98, 129.99]), (7, [199.99, 299.98, 79.95]), (8, [179.97, 299.95, 199.92, 50.0])])

In [8]:
for ois in order_item_subtotals.items():
    print(f'The type of {ois} is {type(ois)}')

The type of (1, [299.98]) is <class 'tuple'>
The type of (2, [199.99, 250.0, 129.99]) is <class 'tuple'>
The type of (4, [49.98, 150.0, 199.92]) is <class 'tuple'>
The type of (5, [299.98, 299.95, 99.96, 299.98, 129.99]) is <class 'tuple'>
The type of (7, [199.99, 299.98, 79.95]) is <class 'tuple'>
The type of (8, [179.97, 299.95, 199.92, 50.0]) is <class 'tuple'>

* Let us check the type of each of the value in our `dict` (2nd element in each of the tuple generated by `items`)

In [9]:
for ois in order_item_subtotals.items():
    print(f'The type of {ois[1]} is {type(ois[1])}')

The type of [299.98] is <class 'list'>
The type of [199.99, 250.0, 129.99] is <class 'list'>
The type of [49.98, 150.0, 199.92] is <class 'list'>
The type of [299.98, 299.95, 99.96, 299.98, 129.99] is <class 'list'>
The type of [199.99, 299.98, 79.95] is <class 'list'>
The type of [179.97, 299.95, 199.92, 50.0] is <class 'list'>

### Task 1 - Number of items per order

Let us take the **order_item_subtotals** which is of type `dict` where each value is of type list and try to get the number of items per order.
* Convert the `dict` to list like object using `items`.
* Iterate through the list generated and apply `len` on second element. This will get us a new list with tuples, where first element is order id and second element is number of elements.
* Apply `dict` to creat a dict on top of results.

In [10]:
order_item_subtotals = {
    1: [299.98],
    2: [199.99, 250.0, 129.99],
    4: [49.98, 150.0, 199.92],
    5: [299.98, 299.95, 99.96, 299.98, 129.99],
    7: [199.99, 299.98, 79.95],
    8: [179.97, 299.95, 199.92, 50.0]
}

In [11]:
number_of_items_per_order = []
for oi in order_item_subtotals.items():
    number_of_items_per_order.append((oi[0], len(oi[1])))

In [12]:
number_of_items_per_order

[(1, 1), (2, 3), (4, 3), (5, 5), (7, 3), (8, 4)]

In [13]:
dict(number_of_items_per_order)

{1: 1, 2: 3, 4: 3, 5: 5, 7: 3, 8: 4}

### Task 2 - Revenue per order

Let us perform another task to get revenue per order. Most of the logic is same as in the previous task. We just need to use `sum` to get revenue per order.

In [14]:
order_item_subtotals = {
    1: [299.98],
    2: [199.99, 250.0, 129.99],
    4: [49.98, 150.0, 199.92],
    5: [299.98, 299.95, 99.96, 299.98, 129.99],
    7: [199.99, 299.98, 79.95],
    8: [179.97, 299.95, 199.92, 50.0]
}

In [15]:
revenue_per_order = []
for oi in order_item_subtotals.items():
    revenue_per_order.append((oi[0], round(sum(oi[1]), 2)))

In [16]:
revenue_per_order

[(1, 299.98), (2, 579.98), (4, 399.9), (5, 1129.86), (7, 579.92), (8, 729.84)]

In [17]:
dict(revenue_per_order)

{1: 299.98, 2: 579.98, 4: 399.9, 5: 1129.86, 7: 579.92, 8: 729.84}